### Install Sempy

Relevant refferences: 
- [Sempy release blog](https://blog.fabric.microsoft.com/en-us/blog/semantic-link-use-fabric-notebooks-and-power-bi-datasets-for-machine-learning-data-validation-and-more/)
- [Sempy Documentation and tutorials](https://learn.microsoft.com/en-us/fabric/data-science/semantic-link-overview)

In [1]:
# Install sempy package
%pip install -U semantic-link
%pip install semantic-link-labs
import sempy.fabric as fabric
import sempy_labs as labs
from sempy_labs import directlake

# Load extension 
%load_ext sempy

StatementMeta(, 22939087-4769-4e7b-b764-7f9ad076aad5, 17, Finished, Available, Finished)

Requirement already satisfied: semantic-link in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (0.12.3)
Requirement already satisfied: semantic-link-sempy==0.12.3 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link) (0.12.3)
Requirement already satisfied: semantic-link-functions-geopandas==0.12.3 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link) (0.12.3)
Requirement already satisfied: semantic-link-functions-holidays==0.12.3 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link) (0.12.3)
Requirement already satisfied: semantic-link-functions-meteostat==0.12.3 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link) (0.12.3)
Requirement already satisfied: semantic-link-functions-phonenumbers==0.12.3 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link) (0.12.3)
Requirement already satisfied: semantic-link-functions-validators==0.12.3 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link) (0.12.3)
Requirement already satisfied: geopandas in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-functions-geopandas==0.12.3->semantic-link) (1.1.1)
Requirement already satisfied: folium in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-functions-geopandas==0.12.3->semantic-link) (0.20.0)
Requirement already satisfied: mapclassify in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-functions-geopandas==0.12.3->semantic-link) (2.10.0)
Requirement already satisfied: holidays in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-functions-holidays==0.12.3->semantic-link) (0.48)
Requirement already satisfied: meteostat in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-functions-meteostat==0.12.3->semantic-link) (1.7.6)
Requirement already satisfied: phonenumbers in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-functions-phonenumbers==0.12.3->semantic-link) (9.0.19)
Requirement already satisfied: validators in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-functions-validators==0.12.3->semantic-link) (0.35.0)
Requirement already satisfied: clr_loader>=0.2.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (0.2.5)
Requirement already satisfied: fabric-analytics-sdk<1.0.0,>=0.0.2 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (0.0.2)
Requirement already satisfied: graphviz>=0.20.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (0.20.1)
Requirement already satisfied: azure-storage-blob>=12.18.3 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (12.22.0)
Requirement already satisfied: azure-core>=1.29.4 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (1.36.0)
Requirement already satisfied: azure-keyvault-secrets>=4.7.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (4.10.0)
Requirement already satisfied: azure-storage-file-datalake>=12.12.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (12.16.0)
Requirement already satisfied: pyarrow>=12.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (14.0.2)
Requirement already satisfied: pythonnet>=3.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (3.0.1)
Requirement already satisfied: scikit_learn>=1.2.2 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (1.7.2)
Requirement already satisfied: setuptools>=68.2.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (68.2.2)
Requirement already satisfied: tqdm>=4.65.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (4.65.0)
Requirement already satisfied: rich>=13.3.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (13.3.5)
Requirement already satisfied: regex>=2023.8.8 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (2023.10.3)
Requirement already satisfied: pandas>=1.5.3 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (2.1.4)
Requirement already satisfied: pyjwt>=2.4.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (2.4.0)
Requirement already satisfied: pyspark>=3.4.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (3.5.1.5.4.20240407)
Requirement already satisfied: requests>=2.31.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (2.31.0)
Requirement already satisfied: aiohttp>=3.8.6 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (3.9.3)
Requirement already satisfied: IPython>=8.14.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (8.20.0)
Requirement already satisfied: tenacity>=8.2.3 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy==0.12.3->semantic-link) (8.2.3)
Requirement already satisfied: aiosignal>=1.1.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy==0.12.3->semantic-link) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy==0.12.3->semantic-link) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy==0.12.3->semantic-link) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy==0.12.3->semantic-link) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy==0.12.3->semantic-link) (1.9.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-core>=1.29.4->semantic-link-sempy==0.12.3->semantic-link) (4.9.0)
Requirement already satisfied: isodate>=0.6.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-keyvault-secrets>=4.7.0->semantic-link-sempy==0.12.3->semantic-link) (0.6.1)
Requirement already satisfied: cryptography>=2.1.4 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-storage-blob>=12.18.3->semantic-link-sempy==0.12.3->semantic-link) (42.0.2)
Requirement already satisfied: cffi>=1.13 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from clr_loader>=0.2.5->semantic-link-sempy==0.12.3->semantic-link) (1.16.0)
Requirement already satisfied: azure-identity in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fabric-analytics-sdk<1.0.0,>=0.0.2->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (1.15.0)
Requirement already satisfied: fabric-analytics-notebook-plugin in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (0.0.2)
Requirement already satisfied: decorator in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (0.18.1)
Requirement already satisfied: matplotlib-inline in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (2.15.1)
Requirement already satisfied: stack-data in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (0.2.0)
Requirement already satisfied: traitlets>=5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (5.7.1)
Requirement already satisfied: pexpect>4.3 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (4.8.0)
Requirement already satisfied: numpy<2,>=1.23.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pandas>=1.5.3->semantic-link-sempy==0.12.3->semantic-link) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pandas>=1.5.3->semantic-link-sempy==0.12.3->semantic-link) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pandas>=1.5.3->semantic-link-sempy==0.12.3->semantic-link) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pandas>=1.5.3->semantic-link-sempy==0.12.3->semantic-link) (2023.3)
Requirement already satisfied: py4j==0.10.9.7 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pyspark>=3.4.1->semantic-link-sempy==0.12.3->semantic-link) (0.10.9.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests>=2.31.0->semantic-link-sempy==0.12.3->semantic-link) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests>=2.31.0->semantic-link-sempy==0.12.3->semantic-link) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests>=2.31.0->semantic-link-sempy==0.12.3->semantic-link) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests>=2.31.0->semantic-link-sempy==0.12.3->semantic-link) (2024.2.2)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from rich>=13.3.5->semantic-link-sempy==0.12.3->semantic-link) (2.2.0)
Requirement already satisfied: scipy>=1.8.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from scikit_learn>=1.2.2->semantic-link-sempy==0.12.3->semantic-link) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from scikit_learn>=1.2.2->semantic-link-sempy==0.12.3->semantic-link) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from scikit_learn>=1.2.2->semantic-link-sempy==0.12.3->semantic-link) (3.6.0)
Requirement already satisfied: branca>=0.6.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from folium->semantic-link-functions-geopandas==0.12.3->semantic-link) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from folium->semantic-link-functions-geopandas==0.12.3->semantic-link) (3.1.3)
Requirement already satisfied: xyzservices in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from folium->semantic-link-functions-geopandas==0.12.3->semantic-link) (2022.9.0)
Requirement already satisfied: pyogrio>=0.7.2 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from geopandas->semantic-link-functions-geopandas==0.12.3->semantic-link) (0.12.1)
Requirement already satisfied: packaging in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from geopandas->semantic-link-functions-geopandas==0.12.3->semantic-link) (23.1)
Requirement already satisfied: pyproj>=3.5.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from geopandas->semantic-link-functions-geopandas==0.12.3->semantic-link) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from geopandas->semantic-link-functions-geopandas==0.12.3->semantic-link) (2.1.2)
Requirement already satisfied: networkx>=3.2 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from mapclassify->semantic-link-functions-geopandas==0.12.3->semantic-link) (3.6)
Requirement already satisfied: pycparser in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from cffi>=1.13->clr_loader>=0.2.5->semantic-link-sempy==0.12.3->semantic-link) (2.21)
Requirement already satisfied: six in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from isodate>=0.6.1->azure-keyvault-secrets>=4.7.0->semantic-link-sempy==0.12.3->semantic-link) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from jedi>=0.16->IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from jinja2>=2.9->folium->semantic-link-functions-geopandas==0.12.3->semantic-link) (2.1.3)
Requirement already satisfied: mdurl~=0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=13.3.5->semantic-link-sempy==0.12.3->semantic-link) (0.1.0)
Requirement already satisfied: ptyprocess>=0.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pexpect>4.3->IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (0.7.0)
Requirement already satisfied: wcwidth in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (0.2.5)
Requirement already satisfied: msal<2.0.0,>=1.24.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-identity->fabric-analytics-sdk<1.0.0,>=0.0.2->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (1.25.0)
Requirement already satisfied: msal-extensions<2.0.0,>=0.3.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-identity->fabric-analytics-sdk<1.0.0,>=0.0.2->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (1.0.0)
Requirement already satisfied: psutil in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (5.9.0)
Requirement already satisfied: synapseml-utils in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (1.1.6.post2)
Requirement already satisfied: executing in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from stack-data->IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (0.8.3)
Requirement already satisfied: asttokens in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from stack-data->IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (2.0.5)
Requirement already satisfied: pure-eval in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from stack-data->IPython>=8.14.0->semantic-link-sempy==0.12.3->semantic-link) (0.2.2)
Requirement already satisfied: portalocker<3,>=1.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from msal-extensions<2.0.0,>=0.3.0->azure-identity->fabric-analytics-sdk<1.0.0,>=0.0.2->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (2.3.0)
Requirement already satisfied: fluent-logger in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from synapseml-utils->fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (0.10.0)
Requirement already satisfied: gson in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from synapseml-utils->fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (0.0.4)
Requirement already satisfied: msgpack>1.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fluent-logger->synapseml-utils->fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy==0.12.3->semantic-link) (1.0.3)

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: semantic-link-labs in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (0.12.7)
Requirement already satisfied: semantic-link-sempy>=0.12.2 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-labs) (0.12.3)
Requirement already satisfied: anytree in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-labs) (2.13.0)
Requirement already satisfied: polib in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-labs) (1.2.0)
Requirement already satisfied: jsonpath_ng in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-labs) (1.7.0)
Requirement already satisfied: clr_loader>=0.2.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (0.2.5)
Requirement already satisfied: fabric-analytics-sdk<1.0.0,>=0.0.2 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.0.2)
Requirement already satisfied: graphviz>=0.20.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (0.20.1)
Requirement already satisfied: azure-storage-blob>=12.18.3 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (12.22.0)
Requirement already satisfied: azure-core>=1.29.4 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (1.36.0)
Requirement already satisfied: azure-keyvault-secrets>=4.7.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (4.10.0)
Requirement already satisfied: azure-storage-file-datalake>=12.12.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (12.16.0)
Requirement already satisfied: pyarrow>=12.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (14.0.2)
Requirement already satisfied: pythonnet>=3.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (3.0.1)
Requirement already satisfied: scikit_learn>=1.2.2 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (1.7.2)
Requirement already satisfied: setuptools>=68.2.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (68.2.2)
Requirement already satisfied: tqdm>=4.65.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (4.65.0)
Requirement already satisfied: rich>=13.3.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (13.3.5)
Requirement already satisfied: regex>=2023.8.8 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (2023.10.3)
Requirement already satisfied: pandas>=1.5.3 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (2.1.4)
Requirement already satisfied: pyjwt>=2.4.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (2.4.0)
Requirement already satisfied: pyspark>=3.4.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (3.5.1.5.4.20240407)
Requirement already satisfied: requests>=2.31.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (2.31.0)
Requirement already satisfied: aiohttp>=3.8.6 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (3.9.3)
Requirement already satisfied: IPython>=8.14.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (8.20.0)
Requirement already satisfied: tenacity>=8.2.3 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy>=0.12.2->semantic-link-labs) (8.2.3)
Requirement already satisfied: ply in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from jsonpath_ng->semantic-link-labs) (3.11)
Requirement already satisfied: aiosignal>=1.1.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy>=0.12.2->semantic-link-labs) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy>=0.12.2->semantic-link-labs) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from aiohttp>=3.8.6->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.9.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-core>=1.29.4->semantic-link-sempy>=0.12.2->semantic-link-labs) (4.9.0)
Requirement already satisfied: isodate>=0.6.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-keyvault-secrets>=4.7.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.6.1)
Requirement already satisfied: cryptography>=2.1.4 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-storage-blob>=12.18.3->semantic-link-sempy>=0.12.2->semantic-link-labs) (42.0.2)
Requirement already satisfied: cffi>=1.13 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from clr_loader>=0.2.5->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.16.0)
Requirement already satisfied: azure-identity in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fabric-analytics-sdk<1.0.0,>=0.0.2->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.15.0)
Requirement already satisfied: fabric-analytics-notebook-plugin in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.0.2)
Requirement already satisfied: decorator in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.18.1)
Requirement already satisfied: matplotlib-inline in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (2.15.1)
Requirement already satisfied: stack-data in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.2.0)
Requirement already satisfied: traitlets>=5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (5.7.1)
Requirement already satisfied: pexpect>4.3 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (4.8.0)
Requirement already satisfied: numpy<2,>=1.23.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pandas>=1.5.3->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pandas>=1.5.3->semantic-link-sempy>=0.12.2->semantic-link-labs) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pandas>=1.5.3->semantic-link-sempy>=0.12.2->semantic-link-labs) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pandas>=1.5.3->semantic-link-sempy>=0.12.2->semantic-link-labs) (2023.3)
Requirement already satisfied: py4j==0.10.9.7 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pyspark>=3.4.1->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.10.9.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests>=2.31.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests>=2.31.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests>=2.31.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests>=2.31.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (2024.2.2)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from rich>=13.3.5->semantic-link-sempy>=0.12.2->semantic-link-labs) (2.2.0)
Requirement already satisfied: scipy>=1.8.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from scikit_learn>=1.2.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from scikit_learn>=1.2.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /nfs4/pyenv-4efafcdc-f1bc-47bb-8417-d26ad64db83e/lib/python3.11/site-packages (from scikit_learn>=1.2.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (3.6.0)

Requirement already satisfied: pycparser in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from cffi>=1.13->clr_loader>=0.2.5->semantic-link-sempy>=0.12.2->semantic-link-labs) (2.21)
Requirement already satisfied: six in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from isodate>=0.6.1->azure-keyvault-secrets>=4.7.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from jedi>=0.16->IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.8.3)
Requirement already satisfied: mdurl~=0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=13.3.5->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.1.0)
Requirement already satisfied: ptyprocess>=0.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pexpect>4.3->IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.7.0)
Requirement already satisfied: wcwidth in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.2.5)
Requirement already satisfied: msal<2.0.0,>=1.24.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-identity->fabric-analytics-sdk<1.0.0,>=0.0.2->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.25.0)
Requirement already satisfied: msal-extensions<2.0.0,>=0.3.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from azure-identity->fabric-analytics-sdk<1.0.0,>=0.0.2->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.0.0)
Requirement already satisfied: psutil in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (5.9.0)
Requirement already satisfied: synapseml-utils in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.1.6.post2)
Requirement already satisfied: executing in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from stack-data->IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.8.3)
Requirement already satisfied: asttokens in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from stack-data->IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (2.0.5)
Requirement already satisfied: pure-eval in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from stack-data->IPython>=8.14.0->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.2.2)
Requirement already satisfied: portalocker<3,>=1.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from msal-extensions<2.0.0,>=0.3.0->azure-identity->fabric-analytics-sdk<1.0.0,>=0.0.2->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (2.3.0)
Requirement already satisfied: fluent-logger in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from synapseml-utils->fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.10.0)
Requirement already satisfied: gson in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from synapseml-utils->fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (0.0.4)
Requirement already satisfied: msgpack>1.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fluent-logger->synapseml-utils->fabric-analytics-notebook-plugin->fabric-analytics-sdk[online-notebook]<1.0.0,>=0.0.2->semantic-link-sempy>=0.12.2->semantic-link-labs) (1.0.3)

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

Warning: PySpark kernel has been restarted to use updated packages.

In [2]:
# Define variables
_SemanticModelName = "LiveDemo"
_workspace = "Dive into DirectLake"

StatementMeta(, 22939087-4769-4e7b-b764-7f9ad076aad5, 19, Finished, Available, Finished)

# Get dictionary temperature - execute DMV
This in specific queries a DMV operation to get the current data in cache.

In [8]:
%%dax "LiveDemo"

select DIMENSION_NAME, COLUMN_ID, DICTIONARY_SIZE, DICTIONARY_TEMPERATURE, DICTIONARY_LAST_ACCESSED
from $SYSTEM.DISCOVER_STORAGE_TABLE_COLUMNS
order by DICTIONARY_TEMPERATURE desc

StatementMeta(, 22939087-4769-4e7b-b764-7f9ad076aad5, 24, Finished, Available, Finished)

,DIMENSION_NAME,COLUMN_ID,DICTIONARY_SIZE,DICTIONARY_TEMPERATURE,DICTIONARY_LAST_ACCESSED
0,InternetSales,SalesAmount (51),0,18.629475,2025-11-29 10:52:08.166667
1,Product,Color (26),0,10.769748,2025-11-29 10:52:08.166667
2,InternetSales,SalesOrderNumber (36),0,8.777972,2025-11-29 10:50:45.020000
3,Product,ProductKey (20),0,1.822855,2025-11-29 10:52:08.120000
4,InternetSales,ProductKey (39),0,1.822855,2025-11-29 10:52:08.120000
5,Product,StandardCost (25),0,<NA>,NaT
6,Product,EnglishProductName (24),0,<NA>,NaT
7,Product,ProductAlternateKey (21),0,<NA>,NaT
8,Product,SizeRange (29),0,<NA>,NaT
9,Product,Size (28),0,<NA>,NaT
10,Product,Weight (30),0,<NA>,NaT
11,Product,ProductLine (31),0,<NA>,NaT
12,Product,Class (32),0,<NA>,NaT
13,Product,Style (33),0,<NA>,NaT
14,Product,SizeUnitMeasureCode (23),0,<NA>,NaT
15,Date,FullDateAlternateKey (54),0,<NA>,NaT
16,Date,RowNumber 2662979B 1795 4F74 8F37 6A1BA8059B61...,0,<NA>,NaT
17,InternetSales,RowNumber 2662979B 1795 4F74 8F37 6A1BA8059B61...,0,<NA>,NaT
18,InternetSales,SalesOrderLineNumber (37),0,<NA>,NaT
19,InternetSales,CustomerKey (38),0,<NA>,NaT
20,Date,EnglishMonthName (60),0,<NA>,NaT
21,InternetSales,OrderDateKey (40),0,<NA>,NaT
22,InternetSales,DueDateKey (41),0,<NA>,NaT
23,InternetSales,ShipDateKey (42),0,<NA>,NaT
24,InternetSales,PromotionKey (43),0,<NA>,NaT
25,InternetSales,CurrencyKey (44),0,<NA>,NaT
26,InternetSales,SalesTerritoryKey (45),0,<NA>,NaT
27,InternetSales,OrderQuantity (46),0,<NA>,NaT
28,InternetSales,UnitPrice (47),0,<NA>,NaT
29,InternetSales,ExtendedAmount (48),0,<NA>,NaT
30,InternetSales,TaxAmount (52),0,<NA>,NaT
31,Product,EnglishDescription (35),0,<NA>,NaT
32,InternetSales,TotalProductCost (50),0,<NA>,NaT
33,InternetSales,ProductStandardCost (49),0,<NA>,NaT
34,Product,ModelName (34),0,<NA>,NaT
35,Date,DateKey (53),0,<NA>,NaT
36,Product,ListPrice (27),0,<NA>,NaT
37,Date,DayNumberOfWeek (55),0,<NA>,NaT
38,Date,EnglishDayNameOfWeek (56),0,<NA>,NaT
39,Date,DayNumberOfMonth (57),0,<NA>,NaT
40,Date,DayNumberOfYear (58),0,<NA>,NaT
41,Date,WeekNumberOfYear (59),0,<NA>,NaT
42,Product,ProductSubcategoryKey (22),0,<NA>,NaT
43,Date,MonthNumberOfYear (61),0,<NA>,NaT
44,Date,CalendarQuarter (62),0,<NA>,NaT
45,Date,CalendarYear (63),0,<NA>,NaT
46,Date,CalendarSemester (64),0,<NA>,NaT
47,Date,FiscalQuarter (65),0,<NA>,NaT
48,Date,FiscalYear (66),0,<NA>,NaT
49,Date,FiscalSemester (67),0,<NA>,NaT
50,Product,RowNumber 2662979B 1795 4F74 8F37 6A1BA8059B61...,0,<NA>,NaT

# Refresh operations

In [5]:
# Full model refresh - evict all data from cache! Be mindful that directlake will not work after running this command! 

fabric.refresh_dataset(
    workspace=_workspace,
    dataset=_SemanticModelName, 
    refresh_type= 'clearValues'
)
# docs: https://learn.microsoft.com/en-us/python/api/semantic-link-sempy/sempy.fabric?view=semantic-link-python#sempy-fabric-refresh-dataset

StatementMeta(, f76293b2-2f95-4a89-9488-b056cef02a8f, 14, Finished, Available, Finished)

'730778a6-faf0-4d16-9bcf-19c0baa536be'

In [7]:
# List the refresh requests to check if the refresh finished.
fabric.list_refresh_requests(dataset=_SemanticModelName, workspace=_workspace)

StatementMeta(, f76293b2-2f95-4a89-9488-b056cef02a8f, 16, Finished, Available, Finished)

,Id,Request Id,Start Time,End Time,Refresh Type,Service Exception Json,Status,Extended Status,Refresh Attempts
0,1612928878,730778a6-faf0-4d16-9bcf-19c0baa536be,2025-11-27 16:46:55.693000+00:00,2025-11-27 16:47:00.260000+00:00,ViaEnhancedApi,NaN,Completed,Completed,"[{'attemptId': 1, 'startTime': '2025-11-27T16:..."
1,1612928842,65a80c32-2459-09da-b55b-6f947f106db9,2025-11-27 16:46:21.063000+00:00,2025-11-27 16:46:24.853000+00:00,WebModeling,NaN,Completed,Completed,"[{'attemptId': 1, 'startTime': '2025-11-27T16:..."
2,1612867760,f3442819-8b4d-423f-ab15-6108b42bb970,2025-11-27 15:42:09.763000+00:00,2025-11-27 15:42:09.810000+00:00,DirectLakeFraming,NaN,Completed,NaN,[]
3,1612867437,8458b0d7-8a23-9a06-4446-f8cd162dbc09,2025-11-27 15:42:04.410000+00:00,2025-11-27 15:42:09.200000+00:00,WebModeling,NaN,Completed,Completed,"[{'attemptId': 1, 'startTime': '2025-11-27T15:..."

In [14]:
# back to ready mode - after this refresh directlake will work again! 
fabric.refresh_dataset(
    workspace=_workspace,
    dataset=_SemanticModelName, 
    refresh_type= 'automatic'
)

StatementMeta(, 63073b6a-43c6-4779-b698-00db1c88a3b9, 18, Finished, Available, Finished)

FabricHTTPException: 400 Bad Request for url: https://wabi-west-europe-e-primary-redirect.analysis.windows.net/v1.0/myorg/groups/62093ad9-d736-4a4a-a328-3801bd26f2fa/datasets/901e52d3-db93-4c45-a620-db0dcd6a709f/refreshes
Error: {"error":{"code":"InvalidRequest","message":"Invalid dataset refresh request. Another refresh request is already executing"}}
Headers: {'Cache-Control': 'no-store, must-revalidate, no-cache', 'Pragma': 'no-cache', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=utf-8', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'RequestId': 'fa11bdab-b523-48be-a216-7a489f32d7cf', 'Access-Control-Expose-Headers': 'RequestId', 'Date': 'Thu, 06 Feb 2025 13:42:11 GMT'}

In [29]:
# Refresh execution details - check for individual refresh status. 
fabric.get_refresh_execution_details(_SemanticModelName, '851a435b-ddd0-498b-b7ca-fb42dea0bad8', _workspace)

StatementMeta(, 71879c14-d5a5-4736-ba9e-1fb0609fe518, 79, Finished, Available, Finished)

RefreshExecutionDetails(start_time=datetime.datetime(2025, 2, 6, 10, 15, 33, 353000, tzinfo=datetime.timezone.utc), end_time=datetime.datetime(2025, 2, 6, 10, 15, 59, 563000, tzinfo=datetime.timezone.utc), type='Automatic', commit_mode='Transactional', status='Completed', extended_status='Completed', current_refresh_type='Automatic', number_of_attempts=0, objects=           Table      Partition     Status
0        Product        Product  Completed
1  InternetSales  InternetSales  Completed
2           Date           Date  Completed, messages=Empty DataFrame
Columns: [Message, Type]
Index: [], refresh_attempts=   Attempt Id                       Start Time  \
0           1 2025-02-06 10:15:33.861336+00:00

                          End Time  Type
0 2025-02-06 10:15:59.564481+00:00     0  )

# Refresh specific tables

In [10]:
# Objects to refresh, define using a dictionary
objects_to_refresh = [
    {
        "table": "InternetSales"
    },
    {
        "table": "Product"
    }
]

# Refresh the dataset
fabric.refresh_dataset(
    workspace=_workspace,
    dataset=_SemanticModelName, 
    objects=objects_to_refresh,
    refresh_type= 'automatic'
)

StatementMeta(, f76293b2-2f95-4a89-9488-b056cef02a8f, 19, Finished, Available, Finished)

'76dd198f-c8e3-4495-822d-ca668d79ca19'

### Execute Query
Below element executes queries to load the columns related in memory

In [57]:
df = fabric.evaluate_measure(
    # dataset name
    _SemanticModelName,
    # measures
    ["[$ Sales]"], 
    # groupby
    ["Product[Class]"]
)
df

StatementMeta(, 551649c1-0069-48ab-9eb5-c22a592b30b4, 16, Finished, Available, Finished)

  Class        $ Sales
0  <NA>      861774.86
1    H   22340591.8294
2    L    2133761.2238
3    M    4022558.4675

# Sempy labs

In [ ]:
# Check potential unsupported items in semantic model
labs.directlake.show_unsupported_direct_lake_objects(dataset= _SemanticModelName, workspace= _workspace)

StatementMeta(, 71879c14-d5a5-4736-ba9e-1fb0609fe518, 77, Finished, Available, Finished)

(Empty DataFrame
 Columns: [Table Name, Type]
 Index: [],
 Empty DataFrame
 Columns: [Table Name, Column Name, Type, Data Type, Source]
 Index: [],
 Empty DataFrame
 Columns: [From Table, From Column, To Table, To Column, From Column Data Type, To Column Data Type]
 Index: [])

In [11]:
# Check fallback reason
labs.directlake.check_fallback_reason(dataset= _SemanticModelName, workspace= _workspace)

StatementMeta(, f76293b2-2f95-4a89-9488-b056cef02a8f, 20, Finished, Available, Finished)

      Table Name  FallbackReasonID    Fallback Reason Detail
0        Product                 0    No reason for fallback
1  InternetSales                 0    No reason for fallback
2           <NA>                 1  This table is not framed